### ISSUE TITLE
[BUG] "Config is NULL, IllegalPathMode" Fabric 1.21.1 on 0.16.7 Windows 11

### ISSUE THREAD

**Issue by suerion** [Traben-0/EmissiveMod#320]
**Describe the issue**

On my Client, something went wrong, i had loooked on other Mods, if they are the issue, ETF Crash the Client on Startup

Starts on Line 818
https://mclo.gs/WAvUcda#L818

**Crash log**

```
[11:24:13] [main/ERROR]: ETF_load: Config was null, using defaults
[11:24:13] [main/ERROR]: ETF_load: Config was null, using defaults
[11:24:13] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_155
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_155
	at knot/net.minecraft.class_6396.<init>(class_6396.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.<init>(class_128.java:35) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_560(class_128.java:226) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:207) ~[fabric-loader-0.16.7-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	... 2 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "main"]
	at knot/net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47) ~[fabric-api-base-0.4.42+6573ed8c6a-e8e34f419b7c027.jar:?]
	at knot/net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44) ~[fabric-api-base-0.4.42+6573ed8c6a-e8e34f419b7c027.jar:?]
	at knot/com.natamus.collective.fabric.callbacks.CollectiveLifecycleEvents.<clinit>(CollectiveLifecycleEvents.java:9) ~[collective-1.21.1-7.87.jar:?]
	at knot/net.minecraft.class_2477.handler$cio000$collective$loadDefault(class_2477.java:3014) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.method_29429(class_2477.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2477.<clinit>(class_2477.java:36) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_11025(class_2588.java:101) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2588.method_27659(class_2588.java:196) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_27657(class_2561.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5348.getString(class_5348.java:91) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.getString(class_2561.java:45) ~[client-intermediary.jar:?]
	at knot/traben.entity_texture_features.config.ETFConfig$IllegalPathMode.toString(ETFConfig.java:459) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:888) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.TypeAdapters$29.create(TypeAdapters.java:930) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:834) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:812) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:759) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.toJson(Gson.java:736) ~[gson-2.10.1.jar:?]
	at knot/traben.tconfig.TConfigHandler.toJson(TConfigHandler.java:90) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/traben.tconfig.TConfigHandler.toJson(TConfigHandler.java:86) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/traben.tconfig.TConfigHandler.saveToFile(TConfigHandler.java:79) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/traben.tconfig.TConfigHandler.loadFromFile(TConfigHandler.java:117) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/traben.tconfig.TConfigHandler.<init>(TConfigHandler.java:35) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/traben.entity_texture_features.ETF.config(ETF.java:42) ~[entity_texture_features_fabric_1.21-6.2.5.jar:?]
	at knot/net.minecraft.class_2960.handler$dkj000$entity_texture_features$etf$illegalPathOverride(class_2960.java:1519) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_20208(class_2960.java:256) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_45137(class_2960.java:284) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2960.method_60656(class_2960.java:60) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2583.<clinit>(class_2583.java:39) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5250.method_43477(class_5250.java:29) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2561.method_43471(class_2561.java:229) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_155.<clinit>(class_155.java:240) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:123) ~[fabric-loader-0.16.7-1.21.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.7.jar:?]
	... 2 more
```

**Your setup: (please complete the following information):**

- Minecraft version: 1.21.1
- ModLoader: Fabric
- ETF Version 6.2.5

**Comment by Traben-0** [comment]
does it work after deleting your config file?

**Comment by suerion** [comment]
Hey, no i had tried to delete it, but it crash also with the new generated config

**Comment by Traben-0** [comment]
does it work when deleting the config and only having the etf mod loaded?

**Comment by suerion** [comment]
@Traben-0 that i had not tested yet, because it crash with this issue only with ETF, but if you had an hint, what other mod could be an issue there,

**Comment by suerion** [comment]
had yet disabled a few mods, will disable collective soon, to test all issues whats added in the stacktrace

https://mclo.gs/pGvQmua

**Comment by suerion** [comment]
OKey, had found the Culprit. :) it is really Collective compat issue

**Comment by suerion** [comment]
Had it upfated an this is given, could you look together with Serilum? 

It is the issue (the server is now running on ubuntu)

https://github.com/Serilum/.issue-tracker/issues/2756
