### ISSUE TITLE
Crash with latest version

### ISSUE THREAD

**Issue by ClayBC** [Traben-0/EmissiveMod#6]
Am getting crashes with this mod after updating to the 2.0 version on CurseForge. Originally, I was getting crashes with badger spawns on betteranimalsplus, so I decided to disable those spawns but am still getting this crash instead. It seems to fix itself when reverting to 1.04

Time: 1/28/22, 1:07 PM
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.client.render.entity.LivingEntityRenderer.handler$ccg000$applyEmissive(LivingEntityRenderer:1047)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:140)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:45)
	at io.github.lucaargolo.terrarianslimes.client.render.entity.slimes.ModdedSlimeEntityRenderer.render(ModdedSlimeEntityRenderer.kt:51)
	at io.github.lucaargolo.terrarianslimes.client.render.entity.slimes.ModdedSlimeEntityRenderer.render(ModdedSlimeEntityRenderer.kt:25)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:135)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1577)
	at net.minecraft.client.render.WorldRenderer.invokeRenderEntity(WorldRenderer)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:584)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:483)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:506)
	at net.minecraft.client.render.WorldRenderer.handler$dhh000$iris$renderTerrainShadows(WorldRenderer:8970)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1253)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Traben-0** [comment]
I have tried both better animals plus & terrarianSlimes (which seems to have been what caused the crash) I could not reproduce this.
can you send your full mod list, describe what you where doing ( just opening a world, just creating a new world, joining a server, in the middle of a game session etc,), and if you have any resourcep[acks on

**Comment by Traben-0** [comment]
I may have accidentally fixed this with something else in [V2.1.0] - can you try it
